### ISSUE TITLE
Armature Imports Incorrectly

### ISSUE THREAD

**Issue by GoldfishCheese** [veryfancypants/hs2_blender_export#14]
Firstly, this is the version list of software I'm using:
HS2 Better Repack - R15
Blender 4.0.2

When I import a new dump there are no errors and the script runs perfectly (I made sure to use the fix provided in the other issue thread), however the armature is noticeably higher than it should be especially in the arms and it caused improper deformation of the mesh (The replacement teeth also float above the head lol). Here is a list of things I've tried:

1) Exporting a default character
2) Running Studio NEOV2 without experimental plugins or any of the other features presented in the BR launcher (Except enabling full-screen which shouldn't have any bearing on this process anyways)
3) Removing shoes entirely before export (Just in case)

Here are two images to better explain the problem:
![Screenshot 2024-08-15 143033](https://github.com/user-attachments/assets/40538d09-bfc1-4d39-bd58-28c6f877b806)
![Screenshot 2024-08-15 143242](https://github.com/user-attachments/assets/54a344ef-2d5e-4c5f-b229-bd9cc14dd084)

Any help/troubleshooting advice will be greatly appreciated!

-Edit: Closed because I can't read

**Comment by Azreo-Sama** [comment]
hey, i cant read either, can u help me 💀

**Comment by maglesil** [comment]
> ### TROUBLESHOOTING
> 
> - Script imports a character without reporting errors, but the armature is acting weird, and, when in T-pose, arm bones aren't aligned vertically with the character's arms:
> 
> May have a few different causes. One possibility is that the Unity dump is wrong (it is for the wrong character, or you've exported the wrong node). It also occurs when importing a character wearing high heels. Remove the shoes and retry. (Most shoes are okay, though. As a general rule, if the character moves up/down when you toggle 'shoes' in Studio Neo, we're going to have trouble.)

I also read the section but don't know how to mitigate this. My character doesn't wear any shoes, and I made sure that the dump is correct (only 1 character is loaded in the studio).

HS2 Better Repack - R16
Blender 4.0.2
