### ISSUE TITLE
Unable to import dump

### ISSUE THREAD

**Issue by zhaixly** [veryfancypants/hs2_blender_export#7]
dumps=[x for x in os.listdir(path) if x.endswith('.txt') and not x.startswith('pose_')]
NotADirectoryError: [WinError 267] 目录名称无效。: 'D:\\cache\\HoneySelect2_ArcticFox_Ver.1.0.1.6\\Export\\20240321114834_小沢\\dump.txt/'

**Comment by veryfancypants** [comment]
You have selected the dump file instead of the directory. You're supposed to browse to the directory and then press the button.
