### ISSUE TITLE
cannot display Eyebrow when import dump

### ISSUE THREAD

**Issue by fatfatcd** [veryfancypants/hs2_blender_export#8]
I used MeshExporter to export the whole model and textures and import it in blender.
When in studioNeoV2, the model looks like:
![HS2](https://github.com/veryfancypants/hs2_blender_export/assets/31812305/934f4a02-4dc9-45e6-b99b-cddac2824fa1)
then in blender, the model display without eyebrows:
![blender](https://github.com/veryfancypants/hs2_blender_export/assets/31812305/4cf63820-77da-4cd7-89d9-31ffd0189fd6)
I check my textures and i find that head textures exported without eyebrows?
![blender_texture](https://github.com/veryfancypants/hs2_blender_export/assets/31812305/5e05d0de-5ceb-4556-9ac0-96dcd3eb4fc0)
And i tried to adjust my parameters and checked the loading files, such as "eyebrows colors" "eyebrows textures" in blender but no effects.
I am a newbee in hs2 and blender, how can i fix this?

**Comment by veryfancypants** [comment]
The eyebrows are a separate texture, the head material shader overlays them on top of the head texture. Their coordinates are adjustable. By default they should appear roughly in the right place, but if the model has a custom head mesh, you may need to tweak them.
![image](https://github.com/veryfancypants/hs2_blender_export/assets/38112158/69cc2f14-e758-4a10-b2ab-17fde1337028)

**Comment by fatfatcd** [comment]
> The eyebrows are a separate texture, the head material shader overlays them on top of the head texture. Their coordinates are adjustable. By default they should appear roughly in the right place, but if the model has a custom head mesh, you may need to tweak them. ![image](https://private-user-images.githubusercontent.com/38112158/340020836-69cc2f14-e758-4a10-b2ab-17fde1337028.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg1MDU0MjQsIm5iZiI6MTcxODUwNTEyNCwicGF0aCI6Ii8zODExMjE1OC8zNDAwMjA4MzYtNjljYzJmMTQtZTc1OC00YTEwLWIyYWItMTdmZGUxMzM3MDI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE2VDAyMzIwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY4ZTZjODRmMjYyZWZiNWRlZTdiNjU5Y2Y0YTMzYzdjNDQ2NGYxYTUxOWU3ZDhkNWUzNTM3YmJkZThhMjZhN2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-DBRfxS_Vl9b25nhUcaLjRxtnaZekqLrr_lZ8VMkcOk)

Thx for ur reply! I adjusted these parms and the eyebrow seemed to be moved to right place!
![image](https://github.com/veryfancypants/hs2_blender_export/assets/31812305/46870214-f2e3-4ef9-87f4-c9036544a6e4)
But i want to know whether the eyebrow texture is in the same position as the model in game?
